accounts/urls.py
from django.urls import path, re_path, include
from accounts import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('reset/',
    auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html',
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt'
    ),
    name='password_reset'),
    path('reset/done/',
    auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
    name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
    name='password_reset_confirm'),
    path('reset/complete/',
    auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
    name='password_reset_complete'),
    path('settings/password/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'),
    name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
    name='password_change_done'),
]

app/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from app import views

urlpatterns = [
    path('blog/', views.index, name='index'),
    path('blog/add/', views.add, name='add'),
    path('blog/edit/<int:entry_id>/', views.edit, name='edit'),
]

cbv/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('app.urls')),
    path('', include('school.urls')),
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

school/urls.py
from django.contrib import admin
from django.urls import path, include

from school.views import IndexList, StudentList
from . import views
from school.models import Classes, Student, Subject, OptionalSubject
app_name = 'school'
urlpatterns = [
    path('', IndexList.as_view(), name='index'),
    path('class/<int:pk>/', views.StudentList.as_view(), name='classes'),
    path('class/<int:pk>/student/<int:student_pk>/', views.student_detail.as_view(), name='student'),
    path('class/newclass/', views.ClassCreate.as_view(), name='newclass'),
    path('class/<int:pk>/editclass/', views.ClassUpdate.as_view(), name='editclasses'),
    path('class/<int:pk>/deleteclass/', views.ClassDeleteView.as_view(), name='deleteclasses'),
    path('class/newstudent/', views.StudentCreate.as_view(), name='newstudent'),
    path('class/<int:pk>/student/<int:student_pk>/edit', views.StudentUpdate.as_view(), name='editstudent'),
    path('class/<int:pk>/student/<int:student_pk>/deletestudent/', views.StudentDelete.as_view(), name='deletestudent'),      
    path('sub/', views.SubjectList.as_view(), name='sub'),
    path('subject/', views.SubjectStudentList.as_view(), name='subject')
]

school/models.py
from django.db import models
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect


class Classes(models.Model):
    standard = models.CharField(max_length=250)
    division = models.CharField(max_length=25)

    def get_absolute_url(self):
        return reverse('school:classes', kwargs={'pk': self.pk })
 
    def __str__(self):
        return self.standard

class Subject(models.Model):
    name = models.CharField(max_length=200)
    standard = models.ForeignKey(Classes, related_name="student_class", on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

class OptionalSubject(models.Model):
    name = models.CharField(max_length=200)
    standard = models.ForeignKey(Classes, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=250)
    standard = models.ForeignKey(Classes, related_name="student_classes", on_delete=models.CASCADE)
    division = models.CharField(max_length=25)
    subject = models.ForeignKey(Subject, related_name="subject", null=True, on_delete=models.CASCADE)
    optn_subject = models.ForeignKey(OptionalSubject, on_delete=models.CASCADE)
    
    def get_absolute_url(self):
        return reverse('school:student', kwargs={'pk': self.standard.pk ,'student_pk': self.pk} )
    
    def __str__(self):
        return self.name 

school/forms.py
from django import forms
from school.models import Classes, Student

class ClassModelForm(forms.ModelForm):
    class Meta:
        model = Classes
        fields =[
            'standard', 'division'
        ]


class StudentModelForm(forms.ModelForm):
    class Meta:
        model = Student
        fields =[
            'name',
            'standard', 
            'division', 
            'subject', 
            'optn_subject'
        ]

school/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.http import HttpResponse
from school.models import Classes, Student, Subject, OptionalSubject
from django.utils.decorators import method_decorator
from django.views.generic import View, TemplateView, ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from school.forms import ClassModelForm, StudentModelForm




class ClassObjectMixin(object):
    model = Classes
    
    def get_object(self):
        id = self.kwargs.get('pk')
        obj= None
        if id is not None:
            obj = get_object_or_404(self.model, id=id)
        return obj

class StudentObjectMixin(object):
    model = Student
    
    def get_object(self):
        
        obj = get_object_or_404(Student, standard__pk=self.kwargs.get('pk'), pk=self.kwargs.get('student_pk'))
        return obj



# class IndexList(ListView):
#     model = Classes
#     context_object_name = 'classes'

class IndexList(View):
    template_name = 'school/classes_list.html'
    queryset = Classes.objects.all()

    def get_queryset(self):
        return self.queryset

    def get(self, request, *args, **kwargs):
        context = { 'object_list': self.get_queryset }
        return render(request, self.template_name, context)

@method_decorator(login_required, name='dispatch')
class StudentList(generic.DetailView):
    model = Classes
    context_object_name = 'students'
    template_name = 'school/student_list.html'

# def student_detail(request, pk, student_pk):
#     student = get_object_or_404(Student, standard__pk=pk, pk=student_pk)
#     return render(request, 'school/student_detail.html', {'student': student})

class student_detail(StudentObjectMixin, View):
    template_name = 'school/student_detail.html'
    
    def get(self, request, *args, **kwargs):
        context = { 'student': self.get_object() }
        return render(request, self.template_name, context)


# class ClassCreate(CreateView):
#     model = Classes
#     fields = ['standard', 'division']

class ClassCreate(View):
    template_name = "school/classes_form.html"

    def get(self, request, *args, **kwargs):
        form = ClassModelForm()
        context = {'form': form}
        return render(request, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        form = ClassModelForm(request.POST)
        if form.is_valid():
            form.save()
            form = ClassModelForm()
        context = {'form': form}
        return render(request, self.template_name, context)

# class ClassUpdate(UpdateView):
#     model = Classes
#     fields = ['standard', 'division']

class ClassUpdate(ClassObjectMixin, View):
    template_name = "school/classes_form.html"
    
    def get(self, request, id=None, *args, **kwargs):
        context ={}
        obj = self.get_object()
        if obj is not None:
            form = ClassModelForm(instance=obj)
            context['object'] = obj
            context['form'] = form
        return render(request, self.template_name, context)

    def post(self, request, id=None, *args, **kwargs):
        context = {}
        obj = self.get_object()
        if obj is not None:
            form = ClassModelForm(request.POST, instance=obj)
            if form.is_valid():
                form.save()
                form = ClassModelForm
            context['object'] = obj
            context['form'] = form
        return render(request, self.template_name, context)

class ClassDeleteView(ClassObjectMixin, View):
    template_name = 'school/class_delete.html'

    def get(self, request, id=None, *args, **kwargs):
        context = {}
        obj = self.get_object()
        if obj is not None:
            context['object'] = obj
        return render(request, self.template_name, context)

    def post(self, request, id=None, *args, **kwargs):
        context = {}
        obj = self.get_object()
        if obj is not None:
            obj.delete()
            context['object'] = None
            return redirect('school:index')
        return render(request, self.template_name, context)

# class StudentCreate(CreateView):
#     model = Student
#     fields = ['name', 'standard', 'division', 'subject', 'optn_subject']    

class StudentCreate(View):
    template_name = "school/student_form.html"

    def get(self, request, *args, **kwargs):
        form = StudentModelForm()
        context = {'form': form}
        return render(request, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        form = StudentModelForm(request.POST)
        if form.is_valid():
            form.save()
            form = StudentModelForm()
        context = {'form': form}
        return render(request, self.template_name, context)    

# class StudentUpdate(UpdateView):
#     model = Student
#     fields = ['name', 'standard', 'division', 'subject', 'optn_subject']

class StudentUpdate(StudentObjectMixin, View):
    template_name = "school/student_update_form.html"

    def get(self, request, id=None, *args, **kwargs):
        context ={}
        obj = self.get_object()
        if obj is not None:
            form = StudentModelForm(instance=obj)
            context['object'] = obj
            context['form'] = form
        return render(request, self.template_name, context)

    def post(self, request, id=None, *args, **kwargs):
        context = {}
        obj = self.get_object()
        if obj is not None:
            form = StudentModelForm(request.POST, instance=obj)
            if form.is_valid():
                form.save()
                form = StudentModelForm
            context['object'] = obj
            context['form'] = form
        return render(request, self.template_name, context)        
    
# class StudentDelete(DeleteView):
#     model = Student
#     success_url = reverse_lazy('school:index')

class StudentDelete(StudentObjectMixin, View):
    template_name = 'school/student_confirm_delete.html'

    def get(self, request, id=None, *args, **kwargs):
        context = {}
        obj = self.get_object()
        if obj is not None:
            context['object'] = obj
        return render(request, self.template_name, context)

    def post(self, request, id=None, *args, **kwargs):
        context = {}
        obj = self.get_object()
        if obj is not None:
            obj.delete()
            context['object'] = None
            return redirect('school:index')
        return render(request, self.template_name, context)

class SubjectStudentList(ListView):
    model = Classes
    context_object_name = 'classes'
    template_name = 'school/subject_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['student_hindi'] = Student.objects.filter(optn_subject__name='Hindi')
        context['student_sanskrit'] = Student.objects.filter(optn_subject__name='Sanskrit')  
        return context 

class SubjectList(ListView):
    model = Subject
    context_object_name = 'sub'
    template_name = 'school/list.html'

    def get_context_data(self, *args, **kwargs):
        
        context = super().get_context_data(**kwargs)
        option = OptionalSubject.objects.all()
        for sub in option:
            var = 'student_' + sub.name
            context['student_' + sub.name] = Student.objects.filter(optn_subject__name=sub.name)
            
            context['x'] = var
        
        return context 

templates/school/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}School{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Charmonman" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    {% block stylesheet %}{% endblock %}
  </head>
  <body>
    {% block body %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'school:index' %}">school</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="mainMenu">
                <form class="form-inline ml-auto">
                  <a href="{% url 'school:newstudent' %}" class="btn btn-primary ml-2">Create a New Student</a>
                </form>
                {% if user.is_authenticated %}
                  <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                      </a>
                      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                        <a class="dropdown-item" href="#">My account</a>
                        <a class="dropdown-item" href="#">Change password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
                      </div>
                    </li>
                  </ul>
                {% else %}
                  <form class="form-inline ml-auto">
                    <a href="{% url 'accounts:login' %}" class="btn btn-outline-secondary">Log in</a>
                    <a href="{% url 'accounts:signup' %}" class="btn btn-primary ml-2">Sign up</a>
                  </form>
                {% endif %}
              </div>
    </nav>
    

    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
    </div>
    {% endblock body %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/school/class_create.html
{% extends 'school/base.html' %}

{% block content %}
<form action='.' method='POST'>{%csrf_token%}
    {{form.as_p}}

    <input type='submit' value='Save' />

</form>
{% endblock %}1

templates/school/class_delete.html
{% extends 'school/base.html' %}

{% block content %}
<form action='.' method='POST'>{% csrf_token %}
    <h1>Do you want to delete the class"{{ object.title }}"?</h1>
    <p><input type='submit' value='Yes'/><a href='../'>Cancel</a></p>

</form>
{% endblock %}

templates/school/class_update.html
{% extends 'school/base.html' %}

{% block content %}
<h1>Update: {{object.id }} - {{ object.title }}</h1>

<form action='.' method='POST'>{% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Save' />
</form>




{% endblock %}

templates/school/classes_form.html
{% extends 'school/base.html' %}

{% block breadcrumb %}
{% endblock %}

{% block content %}

<form method="post">{% csrf_token %}
    {% include 'includes/form.html' %}
    <input type="submit" value="Save">
</form>
{% endblock %}

templates/school/classes_list.html
{% extends 'school/base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Classes</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Class</th>
        <th>Division</th>
        
      </tr>
    </thead>
    <tbody>
        {% for class in object_list %}
        <tr>
          <td>
            <a href="{% url 'school:classes' class.id  %}">{{ class.standard }}</a>
            
          </td>
          <td class="align-middle">{{ class.division }}</td>
          
          
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/school/list.html
{% for a in x %}
{{a}}
{% endfor %}

<p></p>

templates/school/student_confirm_delete.html
{% extends 'school/base.html' %}

{% block breadcrumb %}
{% endblock %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

templates/school/student_detail.html
{% extends 'school/base.html' %}

{% load static %}

{% block breadcrumb %}
  <li class="breadcrumb-item "><a href="{% url 'school:index' %}">Classes</a></li>
  <li class="breadcrumb-item"><a href="{% url 'school:classes' student.standard.pk %}">{{student.standard}} - {{ student.division }}</a></li>
  <li class="breadcrumb-item active">{{ student.name }}</li>

  {% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-3 col-md-3">
    <h2>{{ student.name }}</h2>
    <div class="card" style="width:250px">
      <img class="card-img-top" src="{% static 'img/true.png' %}" alt="Card image" style="width:100%">
      <div class="card-body">
        <h4 class="card-title">{{ student.name }}</h4>
      </div>
      <div class="mb-4 ml-4">
        <a href="{%url 'school:editstudent' student.standard.pk student.pk%}" class="btn btn-primary">Edit</a>
        <a href="{%url 'school:deletestudent' student.standard.pk student.pk%}" class="btn btn-primary">Delete</a>
    </div>
    </div>
    </div>
    
    <div class="col-lg-9 col-md-9">
        <div class="container">
                <h2>Details</h2>
                <br>
                <!-- Nav pills -->
                <ul class="nav nav-pills" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link active" data-toggle="pill" href="#home">Details</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" data-toggle="pill" href="#menu1">Subjects</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" data-toggle="pill" href="#menu2">Optional Subjetcs</a>
                  </li>
                </ul>
              
                <!-- Tab panes -->
                <div class="tab-content">
                  <div id="home" class="container tab-pane active"><br>
                    <h3>Details</h3>
                    <div class="container">
                            <table class="table table-borderless">
                              
                              <tbody>
                                <tr>
                                  <td>Name</td>
                                  <td><strong>{{ student.name }}</strong></td>
                                </tr>
                                <tr>
                                  <td>Class</td>
                                  <td><strong>{{ student.standard }}</strong></td>
                                </tr>
                                <tr>
                                  <td>Division</td>
                                  <td><strong>{{ student.division }}</strong></td>

                                </tr>
                              </tbody>
                            </table>
                          </div>
                          
                  </div>
                  <div id="menu1" class="container tab-pane fade"><br>
                    <h3>Subjects</h3>
                    <div class="container">
                               
                            <table class="table table-borderless">
                              
                              <tbody>
                                <tr>
                                  <td>Subject 1</td>
                                  <td>{{ student.subject }}</td>
                                  
                                </tr>
                                </tbody>
                            </table>
                          </div>
                          
                  </div>
                  <div id="menu2" class="container tab-pane fade"><br>
                    <h3>Optional Subjects</h3>
                    <div class="container">
                            <table class="table table-borderless">
                              <tbody>
                                <tr>
                                  <td>Optional Subject - 1</td>
                                  <td><a href="{% url 'school:subject' %}">{{ student.optn_subject }}</a></td>
                                </tr>
                                </tbody>
                            </table>
                          </div>
                          
                  </div>
                </div>
        </div>
    </div> 
</div>                      
    
{% endblock %}

templates/school/student_form.html
{% extends 'school/base.html' %}

{% block breadcrumb %}
{% endblock %}

{% block content %}

<form method="post">{% csrf_token %}
    {% include 'includes/form.html' %}
    <input type="submit" value="Save">
</form>
{% endblock %}

templates/school/student_list.html
{% extends 'school/base.html' %}
{% load static %}
{% block breadcrumb %}
  <li class="breadcrumb-item "><a href="{% url 'school:index' %}">Classes</a></li>
  <li class="breadcrumb-item active">{{students.standard}} - {{ students.division }}</li>
{% endblock %}

{% block content %}
    <div class="row">
    {% for student in students.student_classes.all %}
        
            <div class="col-lg-4 col-md-4">
            <div class="card mb-2" >
              <img class="card-img-top" src="{% static 'img/true.png' %}" alt="Card image" style="width:100%">
              <div class="card-body">
                
                <h4 class="card-title"><a href="{% url 'school:student' students.pk student.pk  %}">{{ student.name }}</a></h4>
                <h4 class="card-title">{{students.standard}} - {{ students.division }}</h4>
                <a href="#" class="btn btn-primary">See Profile</a>
              </div>
            </div>
            </div>
        
    {% endfor %}
    </div>
{% endblock %}

templates/school/student_update_form.html
{% extends 'school/base.html' %}

{% block breadcrumb %}
{% endblock %}

{% block content %}
<div class="container text-right">
    <a href="#" class="btn btn-primary">Edit</a>
    <a href="#" class="btn btn-primary">Delete</a>
</div>
<form method="post">{% csrf_token %}
    {% include 'includes/form.html' %}
    <input type="submit" value="Update">
</form>
{% endblock %}

templates/school/subject_list.html
{% extends 'school/base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Classes</li>
{% endblock %}

{% block content %}

<h1>Hindi</h1>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Student</th>
        <th>Class</th>
        <th>Division</th>
        
      </tr>
    </thead>
    <tbody>
        {% for student in student_hindi %}
        <tr>
          <td>
            <a href="{% url 'school:student' student.standard.pk student.pk  %}">{{ student.name }}</a>
            
          </td>
          <td class="align-middle">{{ student.standard }}</td>
          <td class="align-middle">{{ student.division }}</td>
          
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <h1>Sanskrit</h1>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Student</th>
        <th>Class</th>
        <th>Division</th>
        
      </tr>
    </thead>
    <tbody>
        {% for student in student_sanskrit %}
        <tr>
          <td>
            <a href="{% url 'school:student' student.standard.pk student.pk  %}">{{ student.name }}</a>
            
          </td>
          <td class="align-middle">{{ student.standard }}</td>
          <td class="align-middle">{{ student.division }}</td>
          
          
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}